#!/bin/sh

#  By ZeroLinux - 18/07/2013
# 
#  Copyright 2013 Carlos D. Rincon <carlosrincon2005@gmail.com>
#  The development of this tool was supported by Projeto Addons (www.projeto addons.com.br)
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

#In this file stratos acts as Blacklist of users
ctrlStratos(){
	action="$1"
	local address="$2"
	if [ "$action" = "add" ]; then
		#iptables -A FORWARD -p tcp --dport 443 -s ${address} -j lockon
		iptables -I FORWARD -p tcp --dport 443 -s ${address} -m state --state NEW,RELATED,ESTABLISHED -j lockon
		iptables -t mangle -I PREROUTING -p tcp --dport 80 -s ${address} -j lockon
	else
		#iptables -D FORWARD -p tcp --dport 443 -s ${address} -j lockon
		iptables -D FORWARD -p tcp --dport 443 -s ${address} -m state --state NEW,RELATED,ESTABLISHED -j lockon
		iptables -t mangle -D PREROUTING -p tcp --dport 80 -s ${address} -j lockon
	fi
}

fn_ssl(){
	local address="${2}/32"
	case $1 in
		create)
			iptables -N lockon
		;;
		add)
			iptables -D lockon -p tcp -j REJECT --reject-with tcp-reset
			iptables -A lockon -d ${address} -j RETURN
			iptables -A lockon -p tcp -j REJECT --reject-with tcp-reset
		;;
		load) iptables -A lockon -d ${address} -j RETURN;;
		end) iptables -A lockon -p tcp -j REJECT --reject-with tcp-reset;;
		remove)
			iptables -D lockon -d ${address} -j RETURN
		;;
		delete)
			iptables -F lockon
			iptables -X lockon
		;;
	esac
}

fn_http(){
	local address="${2}/32"
	case $1 in
		create)
			iptables -t mangle -N lockon
		;;
		add)
			iptables -t mangle -D lockon -p tcp -j MARK --set-mark 99
			iptables -t mangle -A lockon -d ${address} -j RETURN
			iptables -t mangle -A lockon -p tcp -j MARK --set-mark 99
		;;
		load) iptables -t mangle -A lockon -d ${address} -j RETURN;;
		end) iptables -t mangle -A lockon -p tcp -j MARK --set-mark 99;;
		remove)
			iptables -t mangle -D lockon -d ${address} -j RETURN
		;;
		delete)
			iptables -t mangle -F lockon
			iptables -t mangle -X lockon
		;;
	esac
}

ctrlURL(){
	action="$1" # add | delete
	local address="$2"
	conntype="$3"
	if [ ! -n "$conntype" ]; then
		fn_ssl ${1} "$address"
		fn_http ${1} "$address"
	else
		fn_http ${1} "$address"
	fi
}

loadProfile(){
	echo "loading Profile..."
	fn_http "create"
	fn_ssl "create"
	for i in $(ls $DBPATH); do
		if [ "$(grep "$i" $HELPER/ssl.db)" ]; then
			SSL="true"
		else
			SSL="false"
		fi
		while read ip; do
			echo "adding ips of $i to http"
			fn_http load "$ip"
			if [ "$SSL" = "true" ]; then
				echo "adding ips of $i to https"
				fn_ssl load "$ip"
			fi
		done < ${DBPATH}/${i}
	done
	echo "clossing http and https..."
	fn_http end
	fn_ssl end
	echo "adding ips to stratos..."
	while read ip comment; do
		ctrlStratos "add" "$ip"
	done < $STRATOSFILE
}

unloadProfile(){
	echo "unloading profile..."
	echo "unloading stratos"
	while read ip comment; do
		ctrlStratos "del" "$ip"
	done < $STRATOSFILE
	echo "unloading http"
	fn_http delete
	echo "unloading https"
	fn_ssl delete
	echo "ready"
}
